let mock = [{
//     id: 4,
//     day: "21-03-21",
//     name: "School",
//     time: "8 AM",
//     location: "BYU",
//     details: "Don't fail those classes"
//   },
//   {
//     id: 8,
//     day: "21-03-21",
//     name: "School",
//     time: "8 AM",
//     location: "BYU",
//     details: "Don't fail those classes"
//   },
//   {
    id: 7,
    day: "21-03-21",
    name: "School",
    time: "8 AM",
    location: "BYU",
    details: "Don't fail those classes",
    people: ["march"],
  },
  {
    id: 5,
    day: "21-04-22",
    name: "Sleep",
    time: "12 AM",
    location: "Bed",
    details: "Go to bed on time. You can do it!!",
    people: ["march"],
  },
  {
    id: 6,
    day: "21-03-21",
    name: "Movie Night",
    time: "8 PM",
    location: "Lounge",
    details: "The Princess Bride. Bring donuts",
    people: [{
        id: "tkautz",
        name: "Truman",
        email: "tilatrivia@gmail.com",
        Address: "Kentucky",
      }, 
      {
        id: "march",
        name: "Maria",
        email: "dinosaurswhosneeze@gmail.com",
        Address: "Texas",
      },
      {
        id: "lgip",
        name: "Lizzy",
        email: "lizilla@gmail.com",
        Address: "Utah",
      },
      {
        id: "igram",
        name: "Isaac",
        email: "isaac.graham@gmail.com",
        Address: "Ohio",
      },],
  },
  {
        day: "21-03-26",
        id: "1376ce0b-022f-3853-bbb4-39333e6c232f",
        name: "Passover",
        time: "5 PM",
        location: "East",
        details: "GEt rid of the yeast.",
        people: ["march"],
    },
    {
        day: "21-03-21",
        id: "a077b4bf-5640-32de-aa27-577de861f37c",
        name: "WRESTLE MANIA.",
        time: "6 AM",
        location: "North",
        details: "Beat up maria .",
        people: ["march"],
    },
    {
        day: "21-03-13",
        id: "427e5a46-eb99-31b5-970c-541582d530a6",
        name: "Bank Robbery",
        time: "5 PM",
        location: "South",
        details: "Don't tell the fuzz.",
        people: [{
            id: "tkautz",
            name: "Truman",
            email: "tilatrivia@gmail.com",
            Address: "Kentucky",
          }, 
          {
            id: "march",
            name: "Maria",
            email: "dinosaurswhosneeze@gmail.com",
            Address: "Texas",
          },
          {
            id: "lgip",
            name: "Lizzy",
            email: "lizilla@gmail.com",
            Address: "Utah",
          },
          {
            id: "igram",
            name: "Isaac",
            email: "isaac.graham@gmail.com",
            Address: "Ohio",
          },],
    },
    {
        day: "21-03-03",
        id: "87b32790-7e0b-3db3-aa91-04aaeb8dd7e3",
        name: "Dating Derby Beginning",
        time: "6 AM",
        location: "Port",
        details: "DAte ALL da bois",
        people: ["march"],
    },
    {
        day: "21-03-26",
        id: "1edb8ae5-2a53-3f9f-a9f0-378a58d53237",
        name: "Dating Derby Completion",
        time: "9 PM",
        location: "New",
        details: "Maria won't win .",
        people: ["march"],
    },
    {
        day: "21-03-30",
        id: "f647e5e4-cc8b-332a-b6f3-3651f29952cb",
        name: "Dentist.",
        time: "9:30AM",
        location: "Vancouver,WA",
        details: "You know the drill.",
        people: [{
            id: "tkautz",
            name: "Truman",
            email: "tilatrivia@gmail.com",
            Address: "Kentucky",
          }, 
          {
            id: "march",
            name: "Maria",
            email: "dinosaurswhosneeze@gmail.com",
            Address: "Texas",
          },
          ],
    },
    {
        day: "21-03-30",
        id: "990b2fe0-742d-3134-9237-9a135d4f4e0c",
        name: "FInal exam for Roman history class.",
        time: "9 PM",
        location: "South",
        details: "Bona Fortuna",
        people: ["march"],
    },
    {
        day: "21-04-02",
        id: "867c6121-eb2c-34b2-ae8a-a939b78d6436",
        name: "Slap an old lady day.",
        time: "4 AM",
        location: "In her face",
        details: "NO regrets.",
        people: ["march"],
    },
    {
        day: "21-04-21",
        id: "864ac944-9caa-37b4-af5e-a00376eb0828",
        name: "Rome's Birthday",
        time: "12 PM",
        location: "At MAria's house",
        details: "PLease bring an offering.",
        people: ["march"],
    },
    {
        day: "21-04-21",
        id: "3edab799-08ea-33a2-b2dc-a546fcaebb3d",
        name: "Battle of San Jacinto",
        time: "12 PM",
        location: "West",
        details: " TExas is a country now",
        people: ["march"],
    },
    {
        day: "21-03-21",
        id: "3cdcf3ba-00ac-3760-b774-bd6d83bd234c",
        name: "Date with Truman",
        time: "10 AM",
        location: "East",
        details: "WHAT A MAN.",
        people: ["march"],
    },
    {
        day: "21-02-17",
        id: "91868b02-5093-3f7e-b80d-3669005e40ac",
        name: "Date with Andy.",
        time: "4 PM",
        location: "Lake",
        details: "Read Andy Roman Poetry until he falls in love with me.",
        people: ["march"],
    },
    {
        day: "21-03-09",
        id: "87dec4de-c826-3813-8c12-e8e9e96c1b4a",
        name: "Hug a bunny day",
        time: "4 PM",
        location: "The bun-bun buddies",
        details: "Show the bunny's nearby.",
        people: ["march"],
    },
    {
        day: "21-03-20",
        id: "452ebaff-9e7a-3b9b-bad6-22d4e4906200",
        name: "Lady Hammiffler's pedicure",
        time: "2 PM",
        location: "in her house",
        details: "Get between the toes.",
        people: ["march"],
    },
    {
        day: "21-03-12",
        id: "5c47ef6e-f3e5-374e-8a8d-7b1132ab9146",
        name: "Give Maria some flowers",
        time: "2 PM",
        location: "da house",
        details: "She prefers daffodils",
        people: ["march"],
    },
    {
        day: "21-03-03",
        id: "e5a02569-ad79-36d8-b2c7-d026aacd73c1",
        name: "Sow the seeds .",
        time: "11 PM",
        location: "West farm",
        details: " Plant the corn",
        people: ["march"],
    },
    {
        day: "21-06-05",
        id: "8874aa68-2ca0-3fff-8ed8-72fc20617791",
        name: "D-DAY",
        time: "11 PM",
        location: "Normandy",
        details: "Don't tell Germany.",
        people: ["march"],
    },
    {
        day: "21-04-16",
        id: "71195cd1-067c-3751-8897-11ce73abf9e5",
        name: "Yell at a bird",
        time: "10 AM",
        location: "where it least expects",
        details: "CAW CaW CAW CAW.",
        people: ["march", "lgip"],
    },
    {
        day: "21-04-3",
        id: "93a138d9-33f9-30e5-8f81-3f230684944e",
        name: "General Conference part 1",
        time: "10 AM",
        location: "Utah",
        details: "Listen to the Lord.",
        people: ["march", "lgip"],
    },
    {
        day: "21-04-04",
        id: "6c10589d-57a4-3e99-b50c-cedc49e8f7ab",
        name: "General Conference pt 2.",
        time: "10 AM",
        location: "UT",
        details: " Pack to go to Missouri.",
        people: ["march"],
    },
    {
        day: "21-03-15",
        id: "b46af6f1-3c5c-31b6-86f3-cbd9d4ffdba7",
        name: "Ides of March.",
        time: "11 AM",
        location: "At the feet of Pompey in the forum",
        details: "Bring your own knife.",
        people: ["march"],
    },
    {
        day: "21-03-06",
        id: "860157fe-f195-37c9-97c0-97dc26b97baa",
        name: "Boxing match between Andrew and Truman",
        time: "11 AM",
        location: "South Arena",
        details: "My money's on Andrew.",
        people: ["march"],
    },
    {
        day: "21-03-08",
        id: "675c3cf0-da76-356b-a477-35d8ff6bd8f9",
        name: "The funeral of communism.",
        time: "1 PM",
        location: "East wall",
        details: "Good riddance.",
        people: ["march"],
    },
    {
        day: "21-02-11",
        id: "e4e5cc0f-6cc3-37fa-8dff-4dc0308e0b50",
        name: "The monthly moon cycle",
        time: "8 AM",
        location: "in the body",
        details: " I hate this literally so much.",
        people: ["march"],
    },
    {
        day: "21-04-05",
        id: "958f8aa4-4100-30f3-8477-fa0edc413d98",
        name: "Waffle Party.",
        time: "8 AM",
        location: "My house",
        details: " DO you like waffles? Yee.",
        people: ["march"],
    },
    {
        day: "21-03-15",
        id: "ee62093e-aa99-3762-96e5-c03e762762cd",
        name: "Production of the Phantom of the Opera",
        time: "6 PM",
        location: "South Theatre",
        details: " The phantom is better than Raol.",
        people: ["march", "lgip"],
    },
    {
        day: "21-03-22",
        id: "37ff2662-8f45-31c5-916b-ec837d541858",
        name: "Hike the Y.",
        time: "6 PM",
        location: "East",
        details: "Watch out for RMS.",
        people: ["march"],
    },
    {
        day: "21-03-11",
        id: "6389f88e-216a-3551-85fa-e717ddda87b2",
        name: "Mr. Mcgillicutty is coming to steal your eyes",
        time: "6 PM",
        location: "Port",
        details: "It's his thing. Idk anyomre.",
        people: ["march"],
    },
    {
        day: "21-03-07",
        id: "cfd328e7-8907-3cb8-8d00-a707df70aec5",
        name: "Maria Doctor appointment",
        time: "8 AM",
        location: "Southern Virginia University",
        details: "Do no harm",
        people: ["march", "lgip"],
    },
    {
        day: "21-03-21",
        id: "3bc7b403-2456-3f72-b1c0-d0033cd7b34e",
        name: "The day Abby drops out of college",
        time: "6 AM",
        location: "BYU",
        details: "I might as well at this point.",
        people: ["march"],
    }

]

  export default mock;